[features]
seeds = false

[programs.devnet]
frizzle = "5MhHEjob4xzwmWioHPw9DJccaefogEfdRsD9vAMiN7vt"

[programs.localnet]
frizzle = "5MhHEjob4xzwmWioHPw9DJccaefogEfdRsD9vAMiN7vt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/xd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
